export const officialProfile = {
  name: 'Sigit Purnomo Said, S.A.P.',
  title: 'ANGGOTA DPR RI',
  party: 'F-PAN',
  commission: 'Komisi VIII DPR RI',
  dapil: 'Dapil DKI Jakarta III',
  period: '2024–2029',
  wilayah: 'Jakarta Barat, Jakarta Utara, Kepulauan Seribu',
  photo: '/official/sigit-purnomo-said.jpg',
  focus: [
    'Agama',
    'Sosial',
    'Haji',
    'Bantuan Sosial',
    'Kebencanaan',
    'Perlindungan Anak',
    'Lansia',
    'Penyandang Disabilitas',
    'Kelompok Rentan',
    'Pemberdayaan Sosial Masyarakat',
  ],
};
